/* ============================================================
   NavegaKids — textos-curtos.js
   Relato de testes (profa. Camila): para 8 anos o jogo tinha texto
   demais. No nível Marujo, os textos longos de data.js (aberturas,
   dicas, feedbacks, perguntas...) são trocados por versões curtas;
   no Capitão ficam os textos do roteiro.
   A troca é feita nos próprios objetos de data.js (o original fica
   guardado), então todas as telas usam o texto certo sem mudanças.
   Para editar: o texto da esquerda é o do roteiro (igual ao de
   data.js), o da direita é a versão curta do Marujo.
   ============================================================ */
(() => {
  'use strict';
  const NK = (window.NavegaKids ??= {});
  const { progresso, FASES, ILHAS } = NK;

  const CURTOS = new Map([
    ["Oi, pequeno navegador! Hoje você vai conhecer alguém que recebeu um pedido de amizade de um perfil misterioso. Será que ele é quem diz ser?",
     "Oi, navegador! Um perfil misterioso quer ser seu amigo. Será que ele é quem diz ser?"],
    ["Oi, pequeno navegador! Uma aventura misteriosa espera por você! Complete as 3 atividades para descobrir o segredo desse perfil.",
     "Complete as 3 atividades e descubra o segredo desse perfil!"],
    ["Se você não conhece a pessoa de verdade, não precisa aceitar o pedido. E se ela insistir, ignore ou bloqueie.",
     "Não conhece de verdade? Não aceite. Se insistir, ignore ou bloqueie."],
    ["Um novo amigo apareceu no seu caminho! Mas será que ele é quem diz ser? Pense bem antes de aceitar ou recusar!",
     "Um novo amigo apareceu! Ele é quem diz ser? Pense antes de aceitar."],
    ["Opa! Cuidado, navegador! Você não conhece esse pirata de verdade. Que tal investigar o perfil antes de continuar?",
     "Cuidado! Você não conhece esse pirata. Investigue antes!"],
    ["Boa escolha, pequeno navegador! Você não conhece esse pirata, então é melhor manter distância. Na internet, segurança vem primeiro!",
     "Boa escolha! Você não conhece esse pirata. Segurança primeiro!"],
    ["Todo bom detetive junta pistas antes de decidir. Compare esse perfil com quem você já conhece de verdade!",
     "Detetive junta pistas! Compare com seus amigos de verdade."],
    ["Use a lupa: toque nas partes do perfil que mostram que ele pode não ser confiável.",
     "Use a lupa: toque no que parece suspeito no perfil."],
    ["Pista encontrada! Sem foto de verdade, fica difícil saber quem está do outro lado.",
     "Pista! Sem foto de verdade, não dá pra saber quem é."],
    ["Muito bem, detetive! Foto genérica, nenhum amigo em comum e conta nova: quando aparecem tantas pistas juntas, é melhor não aceitar.",
     "Muito bem, detetive! Com tantas pistas, é melhor não aceitar."],
    ["Isso aí! Quando alguém insiste demais depois de um “não”, o caminho mais seguro é não responder e, se possível, bloquear.",
     "Isso aí! Se insistir depois do “não”, ignore ou bloqueie."],
    ["Vamos pensar de novo: não é preciso explicar nada pra quem você nem conhece. Bloquear também é uma opção segura!",
     "Pense de novo: não precisa explicar nada. Bloquear é seguro!"],
    ["De volta ao mar, navegador! Sua tripulação está crescendo... mas você sabe mesmo quem está a bordo?",
     "De volta ao mar! Você sabe quem está na sua tripulação?"],
    ["Jogar junto é diferente de conhecer de verdade. Convites para lugares privados merecem uma conversa com um adulto.",
     "Jogar junto não é conhecer de verdade. Lugar privado? Fale com um adulto."],
    ["Olha só quem está na sua partida em grupo! O Capitão_Lesma2120 apareceu de novo — dessa vez já “confirmado” sem querer.",
     "Olha quem está na partida: o Capitão_Lesma2120 de novo!"],
    ["Nem todo mundo que joga com você é alguém que você conhece de verdade. Vamos dar uma olhada em quem está aqui?",
     "Nem todo mundo que joga com você é conhecido de verdade."],
    ["Pense: você já encontrou essa pessoa pessoalmente e ela faz parte da sua vida real?",
     "Você já viu essa pessoa na vida real?"],
    ["Jogar junto é diferente de conhecer de verdade — e tudo bem ter os dois tipos de contato, desde que você saiba diferenciar!",
     "Jogar junto é diferente de conhecer de verdade!"],
    ["Um espaço privado com alguém que só conhecemos pela tela… vale pensar duas vezes.",
     "Chat privado com quem só conhece pela tela? Pense duas vezes."],
    ["Opa! Gostar do mesmo jogo não é a mesma coisa que confiar 100%. Bora repensar esse convite?",
     "Opa! Gostar do mesmo jogo não é confiar. Pense de novo!"],
    ["Boa, navegador! Ir para um espaço privado com alguém que você só conhece pela tela merece uma conversa com um adulto antes.",
     "Boa! Chat privado com quem só conhece pela tela? Fale antes com um adulto."],
    ["Uma garrafa cheia de mensagens chegou até seu chat. Vamos ler com atenção antes de responder qualquer coisa?",
     "Chegaram mensagens no seu chat. Leia com atenção!"],
    ["Você não precisa responder a tudo. Elogio demais, pergunta pessoal e pedido de segredo são sinais de alerta.",
     "Você não precisa responder a tudo. Fique de olho nos sinais de alerta!"],
    ["Leia com calma... alguma coisa aqui te deixou com a pulga atrás da orelha?",
     "Leia com calma... alguma coisa parece estranha?"],
    ["Elogio exagerado! Quem quer te agradar demais pode estar tentando ganhar sua confiança.",
     "Elogio demais! Pode ser pra ganhar sua confiança."],
    ["Você achou todos os sinais: elogio exagerado, pergunta pessoal demais e pedido de segredo. Ótimo olho de detetive!",
     "Você achou todos os sinais de alerta. Ótimo detetive!"],
    ["Vamos pensar de novo: perguntas pessoais não precisam de resposta só porque alguém insiste.",
     "Pense de novo: pergunta pessoal não precisa de resposta."],
    ["Isso aí! Você não precisa responder a tudo. Sair da conversa e contar pra um adulto é sempre uma opção válida.",
     "Isso aí! Saia da conversa e conte pra um adulto."],
    ["Psiu... alguém te contou um “segredo só entre vocês dois”. Será que todo segredo é para guardar?",
     "Psiu... alguém pediu um segredo. Todo segredo é para guardar?"],
    ["Segredo que pede silêncio dos adultos merece ser contado. Dados pessoais são só seus e da sua família.",
     "Segredo que esconde dos adultos deve ser contado. Seus dados são só seus."],
    ["Bora separar o que é seguro contar do que é melhor guardar com você e sua família.",
     "Separe o que pode contar do que é só seu e da sua família."],
    ["Isso! Gostos como jogo e cor podem ser conversados. Endereço, escola, senha e fotos ficam com você e sua família.",
     "Isso! Gostos podem ser contados. Endereço, escola, senha e fotos, não."],
    ["Segredo bom é festa surpresa. Segredo que pede silêncio… é outra história.",
     "Segredo bom é festa surpresa. Esse é outro tipo!"],
    ["Segredo bom é tipo festa surpresa — deixa todo mundo feliz depois. Segredo que pede silêncio merece ser contado, viu?",
     "Segredo bom é festa surpresa. Segredo que pede silêncio deve ser contado!"],
    ["Você quebrou o segredo certo! Quando alguém pede pra esconder algo dos adultos, é hora de contar pra alguém de confiança.",
     "Isso! Pediram pra esconder dos adultos? Conte pra alguém de confiança."],
    ["Última missão da Ilha dos Mistérios! Um mapa cheio de pistas espera por você. Vamos mostrar tudo que já aprendeu?",
     "Última missão da ilha! Mostre tudo que você aprendeu!"],
    ["Desconfiar do perfil, não compartilhar dados e contar a um adulto: esse é o mapa dos mistérios.",
     "Desconfiar, não contar dados e chamar um adulto!"],
    ["Os sinais das fases anteriores estão escondidos no mapa. Toque em cada sinal de alerta!",
     "Toque em cada sinal de alerta escondido no mapa!"],
    ["Endereço é dado pessoal e não se conta para quem só conhecemos pela tela.",
     "Endereço é só seu e da sua família."],
    ["Não é preciso explicar nada a quem insiste. Ignorar ou bloquear protege você.",
     "Ignorar ou bloquear protege você."],
    ["Mandou bem em todas as cenas! Você lembra de tudo que aprendeu nas fases 1 a 4.",
     "Mandou bem! Você lembrou de tudo!"],
    ["Sequência perfeita: desconfiar do perfil, não compartilhar dados e contar pra um adulto!",
     "Perfeito: desconfiar, não contar dados e chamar um adulto!"],
    ["Bem-vindo à Ilha das Escolhas, navegador! Aqui você vai treinar como escolher o caminho mais seguro — mesmo quando alguém tenta te levar pra outro lugar.",
     "Bem-vindo à Ilha das Escolhas! Aqui você treina escolhas seguras."],
    ["Depois de bloquear aquele perfil misterioso, um novo contato apareceu no seu caminho... será que é o mesmo tipo de conversa de novo? Complete as 3 atividades para descobrir.",
     "Um novo contato apareceu... Complete as 3 atividades para descobrir!"],
    ["Quando alguém quer levar a conversa para um lugar mais privado, é hora de prestar atenção redobrada.",
     "Quer levar a conversa para um lugar escondido? Atenção!"],
    ["Perceba: ele quer levar a conversa para um lugar mais reservado, longe de outras pessoas. Isso é um sinal para prestar atenção.",
     "Atenção: ele quer conversar longe das outras pessoas!"],
    ["Nem toda porta que parece convidativa leva a um lugar seguro. Vamos abrir com cuidado?",
     "Nem toda porta é segura. Abra com cuidado!"],
    ["Se alguém que você mal conhece quer te levar para outro app, desconfie.",
     "Quem você mal conhece quer outro app? Desconfie!"],
    ["Você abriu todas as portas com cuidado! Espaços com pessoas de confiança são seguros; convites reservados de desconhecidos, não.",
     "Muito bem! Lugar com gente de confiança é seguro."],
    ["Vamos repensar: quando alguém quer sair do olhar de outras pessoas para conversar só com você, isso merece atenção redobrada.",
     "Pense de novo: conversar escondido só com você? Atenção!"],
    ["Boa escolha! Continuar a conversa num lugar onde seus responsáveis podem acompanhar é sempre mais seguro.",
     "Boa! Fique onde seus responsáveis podem ver."],
    ["Às vezes, a resposta certa muda tudo. Vamos treinar juntos algumas respostas de navegador esperto?",
     "A resposta certa muda tudo. Vamos treinar?"],
    ["Dá para ser educado e firme ao mesmo tempo: “Prefiro não falar sobre isso. Vou perguntar pro meu responsável.”",
     "Seja educado e firme: “Prefiro não falar. Vou perguntar pro meu responsável.”"],
    ["Não existe só uma forma de responder — mas algumas são bem mais seguras que outras.",
     "Algumas respostas são mais seguras que outras."],
    ["Vamos pensar de novo: fotos são informações pessoais e não devem ir para quem só conhecemos pela tela.",
     "Pense de novo: foto não é para quem só conhece pela tela."],
    ["Ótima resposta! Firme, educada e ainda chama um adulto de confiança para a conversa.",
     "Ótima resposta! Firme, educada e chama um adulto."],
    ["Vamos pensar de novo: aceitar um segredo é entrar no jogo de quem quer esconder algo dos adultos.",
     "Pense de novo: segredo com estranho não é seguro."],
    ["Escolha um bloco de cada grupo para montar uma resposta segura e educada.",
     "Monte uma resposta segura: um bloco de cada grupo."],
    ["Boa mensagem! Ser educado e firme ao mesmo tempo é uma combinação poderosa.",
     "Boa mensagem! Educada e firme!"],
    ["Quase! Essa mensagem deixa uma brecha. Que tal montar uma resposta educada, firme e que chame um adulto?",
     "Quase! Monte uma resposta firme que chame um adulto."],
    ["Vitória! Uma resposta educada e firme é uma arma e tanto contra pedidos estranhos.",
     "Vitória! Resposta educada e firme vence!"],
    ["Essa resposta deixou uma brecha... Bora escolher a carta mais segura dessa vez?",
     "Essa carta deixou uma brecha. Escolha a segura!"],
    ["Às vezes, a atitude mais corajosa é simplesmente sair da conversa. Vamos descobrir quando é a hora certa?",
     "Às vezes, o mais corajoso é sair da conversa. Vamos ver quando?"],
    ["Sair de uma conversa que incomoda não é falta de educação — é se cuidar.",
     "Sair de uma conversa ruim é se cuidar."],
    ["Toda plataforma tem um jeito de sair de uma conversa. Vamos encontrar o botão certo?",
     "Todo jogo tem um botão de sair. Ache ele!"],
    ["Você achou o botão! Saber onde ele fica ajuda a agir rápido quando a conversa incomoda.",
     "Achou! Agora você sabe sair rápido."],
    ["Isso mesmo! Sair de uma conversa que incomoda não é falta de educação — é se cuidar.",
     "Isso mesmo! Sair de conversa ruim é se cuidar."],
    ["Vamos pensar de novo: você não precisa resolver isso sozinho. Sair e contar pra alguém de confiança também é uma ótima escolha.",
     "Pense de novo: você não precisa resolver sozinho. Conte pra um adulto!"],
    ["Bloquear é uma ferramenta de verdade: impede que a pessoa continue mandando mensagem.",
     "Bloquear faz a pessoa parar de mandar mensagem."],
    ["Nos jogos e aplicativos existe um ícone de bloqueio. Geralmente ele fica no perfil da pessoa ou nos três pontinhos.",
     "Todo app tem um botão de bloquear, no perfil ou nos três pontinhos."],
    ["O escudo não é feitiço mágico, é uma ferramenta de verdade que existe nos aplicativos — e você pode usar sempre que precisar.",
     "O escudo é de verdade e você pode usar sempre que precisar."],
    ["O escudo é para quem te deixa desconfortável e não para quando é só uma discussão do dia a dia.",
     "Escudo é para quem te incomoda, não para briguinha boba."],
    ["Boa! O escudo é para quem insiste em te deixar desconfortável — não pra qualquer discussão do dia a dia.",
     "Boa! Escudo é para quem insiste em te incomodar."],
    ["Escudo ativado! Agora esse contato não pode mais te mandar mensagem. Você protegeu seu próprio espaço — e isso é coisa de navegador experiente.",
     "Escudo ativado! Ele não pode mais te mandar mensagem."],
    ["Última missão da Ilha das Escolhas! Vamos mostrar tudo que você aprendeu sobre fazer escolhas seguras?",
     "Última missão da ilha! Mostre suas escolhas seguras!"],
    ["Reconhecer, pensar e agir: identificar o sinal, responder com firmeza, sair e ativar o escudo.",
     "Ver o sinal, responder firme, sair e bloquear!"],
    ["Estão escondidos aqui os sinais das fases 6 a 9. Consegue achar todos?",
     "Ache os sinais das fases 6 a 9!"],
    ["Toque em cada sinal: convite para sair da plataforma, mensagem estranha, desconforto e o botão de escudo.",
     "Toque nos sinais de alerta e no botão de escudo."],
    ["Alguém que você mal conhece chama para conversar em outro aplicativo, “só nós dois”.",
     "Alguém que você mal conhece chama para outro app, “só nós dois”."],
    ["Espaços reservados longe dos olhares de outras pessoas merecem atenção.",
     "Conversa escondida merece atenção."],
    ["Sombra_das_Marés escreve: “Me passa seu endereço? E vamos conversar em outro aplicativo, só nós dois.”",
     "Sombra_das_Marés: “Me passa seu endereço? Vamos pra outro app?”"],
    ["Isso! Pedido de dado pessoal e convite para sair da plataforma são sinais de alerta.",
     "Isso! Pedir dados e chamar pra outro app é alerta."],
    ["Sair de uma conversa que incomoda não é falta de educação: é se cuidar.",
     "Sair de conversa ruim é se cuidar."],
    ["Sequência de mestre: reconhecer o sinal, responder com firmeza, sair e ativar o escudo!",
     "Perfeito: ver o sinal, responder firme, sair e bloquear!"],
    ["Bem-vindo à Ilha dos Guardiões, navegador! Aqui você vai descobrir que nenhum bom pirata navega sozinho. Todo capitão tem uma tripulação de confiança para chamar quando o mar fica agitado.",
     "Bem-vindo à Ilha dos Guardiões! Nenhum pirata navega sozinho."],
    ["Você já aprendeu a reconhecer os perigos e a fazer escolhas seguras. Agora chegou a hora de reunir o seu time de guardiões. Complete as 3 atividades para montar a sua tripulação de confiança.",
     "Hora de montar seu time de guardiões! Complete as 3 atividades."],
    ["Um guardião é um adulto que você conhece de verdade e em quem confia. Quanto mais guardiões, mais forte fica o seu navio.",
     "Guardião é um adulto que você conhece e em quem confia."],
    ["Conheça a Capitã Bússola: ela explica quem pode apontar o caminho certo.",
     "Conheça a Capitã Bússola!"],
    ["Um guardião é um adulto que você conhece de verdade, que cuida de você e em quem você confia. Vamos descobrir quem faz parte do seu time?",
     "Guardião é um adulto que cuida de você. Quem está no seu time?"],
    ["Arraste (ou toque) as cartas para o convés do navio: quem entra no Time de Confiança?",
     "Arraste para o navio quem é do seu Time de Confiança."],
    ["O seu time de confiança é feito de gente que você conhece na vida real e que cuida de você. Quanto mais guardiões, mais forte fica o seu navio!",
     "Seu time tem gente da vida real que cuida de você!"],
    ["Tripulação formada! Seu time de confiança tem gente que você conhece de verdade e que cuida de você.",
     "Tripulação pronta! Só gente de confiança."],
    ["Vamos repensar: nenhum pirata de verdade encara a tempestade sem chamar a tripulação. Contar para um guardião deixa tudo mais seguro.",
     "Pense de novo: chame a tripulação! Contar a um guardião é mais seguro."],
    ["Isso aí! Chamar um adulto de confiança é uma das atitudes mais corajosas e espertas de um navegador. Você nunca precisa enfrentar o mar sozinho.",
     "Isso aí! Chamar um adulto é coisa de navegador corajoso."],
    ["Às vezes acontece algo que deixa a gente com medo ou vergonha de contar. Mas todo guardião sabe de um truque: falar o que aconteceu é o primeiro passo para ficar seguro de novo.",
     "Às vezes dá medo ou vergonha de contar. Mas contar deixa você seguro!"],
    ["Contar o que aconteceu é sempre a atitude certa, mesmo com medo ou vergonha. A culpa nunca é da criança.",
     "Contar é sempre certo. A culpa nunca é da criança."],
    ["Este navegador carrega sozinho um baú pesadão: é o segredo dele. O que acontece quando ele conta para a Capitã Bússola?",
     "Ele carrega um baú pesado: o segredo. E se ele contar?"],
    ["Guardar sozinho uma coisa que te assusta pesa demais. Dividir com um guardião faz esse peso diminuir.",
     "Segredo assustador pesa. Contar deixa mais leve!"],
    ["Quando alguém mais velho tenta enganar ou assustar uma criança, a culpa nunca é da criança. Bora derrubar esses mitos?",
     "A culpa nunca é da criança. Vamos derrubar os mitos!"],
    ["Mito! Quando um adulto engana ou assusta uma criança, a culpa nunca é dela.",
     "Mito! A culpa nunca é da criança."],
    ["Verdade! Todo mundo sente vergonha às vezes, e contar ajuda a ficar seguro.",
     "Verdade! Mesmo com vergonha, contar ajuda."],
    ["Monte uma frase para pedir ajuda a um guardião. Escolha um bloco de cada grupo.",
     "Monte uma frase para pedir ajuda. Um bloco de cada grupo."],
    ["Você não precisa saber explicar tudo direitinho. É só começar a falar!",
     "É só começar a falar!"],
    ["Perfeito! Você não precisa saber explicar tudo direitinho. É só começar a falar, e um guardião te ajuda com o resto.",
     "Perfeito! É só começar a falar e o guardião ajuda."],
    ["Vamos tentar de novo: mesmo quando é difícil achar as palavras, contar sempre ajuda mais do que guardar sozinho.",
     "Tente de novo: contar ajuda mais que guardar."],
    ["Todo bom navio tem uma bandeira de socorro para pedir ajuda de longe. Na internet também existe um jeito de sinalizar quando algo está errado. Vamos aprender?",
     "Na internet também dá pra pedir socorro. Vamos aprender?"],
    ["Denunciar não é dedurar. É usar uma ferramenta de verdade, de preferência ao lado de um adulto de confiança.",
     "Denunciar não é dedurar. Faça junto com um adulto."],
    ["Nos aplicativos e redes existe o botão Denunciar (ou Reportar). Ele avisa a plataforma sobre alguém que está agindo de forma errada.",
     "O botão Denunciar avisa o app que alguém agiu errado."],
    ["Denunciar é diferente de dedurar. É usar uma ferramenta de verdade para avisar que alguém passou dos limites e proteger você e outras crianças.",
     "Denunciar não é dedurar. Protege você e outras crianças."],
    ["Além dos aplicativos, existem canais oficiais de ajuda, como o Disque 100, que adultos de confiança também podem acionar.",
     "Adultos também podem ligar para o Disque 100."],
    ["Cada aplicativo tem o seu jeito de denunciar, quase sempre escondido nos três pontinhos ou no menu. Vamos caçar esse botão?",
     "O botão de denunciar fica nos três pontinhos ou no menu!"],
    ["Em cada aplicativo, toque no lugar onde fica o menu com a opção Denunciar.",
     "Toque onde fica o menu de Denunciar."],
    ["Você caçou o botão nos três aplicativos! Agora você sabe onde procurar.",
     "Você achou o botão nos três apps!"],
    ["Isso mesmo! Denunciar já é ótimo, e fazer isso ao lado de um guardião é ainda mais forte. Adultos de confiança também podem acionar canais oficiais, como o Disque 100.",
     "Isso! Denunciar com um guardião é mais forte. Tem também o Disque 100."],
    ["Vamos repensar: a denúncia é importante, e você não precisa dar esse passo sozinho. Um guardião pode te acompanhar em cada etapa.",
     "Pense de novo: você não precisa denunciar sozinho. Chame um guardião."],
    ["Um guardião de verdade também cuida da tripulação. E se fosse um amigo seu vivendo uma situação estranha na internet? Vamos aprender a ajudar?",
     "E se um amigo tiver um problema na internet? Vamos ajudar?"],
    ["Um bom amigo não guarda esse tipo de segredo. Ele fica ao lado e ajuda a procurar um guardião.",
     "Bom amigo não guarda esse segredo. Ajuda a chamar um guardião."],
    ["Quando um amigo confia em você para contar uma coisa dessas, ele já está sendo corajoso. Como será que dá para ajudar?",
     "Seu amigo foi corajoso em contar. Como ajudar?"],
    ["Seu amigo Leo contou que um perfil desconhecido manda mensagens estranhas.",
     "Leo recebe mensagens estranhas de um desconhecido."],
    ["Um bom amigo não guarda esse tipo de segredo. Ele fica do lado e ajuda a procurar um guardião.",
     "Bom amigo ajuda a procurar um guardião."],
    ["Ótima escolha! Um bom amigo não guarda esse tipo de segredo. Ele fica do lado e ajuda a procurar um guardião.",
     "Ótima escolha! Bom amigo ajuda a procurar um guardião."],
    ["Isso aí! Acompanhar um amigo até um adulto de confiança é coisa de guardião de verdade. Ninguém precisa enfrentar isso sozinho.",
     "Isso aí! Ir junto com o amigo até um adulto é coisa de guardião."],
    ["Vamos pensar de novo: o seu amigo vai se sentir bem mais seguro se você estiver ao lado dele nessa hora.",
     "Pense de novo: seu amigo fica mais seguro com você do lado."],
    ["Última missão da sua grande aventura, navegador! Chegou a hora de mostrar que você virou um verdadeiro Guardião dos Mares.",
     "Última missão! Mostre que você é um Guardião dos Mares!"],
    ["Reconhecer o perigo, fazer a escolha segura, contar para um adulto de confiança e denunciar quando for preciso.",
     "Ver o perigo, escolher seguro, contar e denunciar!"],
    ["Denunciar protege você e outras crianças. Adultos também podem acionar o Disque 100.",
     "Denunciar protege as crianças. Tem o Disque 100."],
    ["Primeiro reconhecemos, depois escolhemos com segurança, contamos e, se preciso, denunciamos.",
     "Ver, escolher, contar e, se preciso, denunciar."],
    ["Rota completa de guardião: reconhecer, escolher com segurança, contar e denunciar!",
     "Rota completa de guardião!"],
    ["Parabéns Pirata, você venceu a Ilha dos Mistérios! Você ganhou o selo de Observador Atento.",
     "Parabéns, Pirata! Você ganhou o selo de Observador Atento!"],
    ["Parabéns, Pirata! Você venceu a Ilha das Escolhas e ganhou o selo de Guardião das Escolhas Seguras!",
     "Parabéns, Pirata! Você ganhou o selo de Guardião das Escolhas Seguras!"],
    ["Parabéns, Pirata! Você venceu a Ilha dos Guardiões e concluiu toda a sua jornada pelos mares digitais. Você conquistou o selo de Guardião dos Mares!",
     "Parabéns, Pirata! Você terminou a jornada e ganhou o selo de Guardião dos Mares!"]
  ]);

  /* Campos de data.js que podem ter versão curta */
  const CAMPOS = new Set(['texto', 'missao', 'aprendizado', 'pergunta', 'dica', 'fbOk', 'fbBad', 'fb', 'why', 'txt', 'cena', 'q', 'conclusao', 'conclusaoExtra']);

  const originais = new WeakMap();   // objeto de data.js → { campo: texto do roteiro }

  /** Põe os textos do nível atual: curtos no Marujo, os do roteiro no Capitão. */
  function aplicar() {
    const curto = progresso.modo() === 'marujo';
    const visitar = (o) => {
      if (Array.isArray(o)) { o.forEach(visitar); return; }
      if (!o || typeof o !== 'object') return;
      for (const k of Object.keys(o)) {
        const v = o[k];
        if (typeof v !== 'string' || !CAMPOS.has(k)) { visitar(v); continue; }
        let orig = originais.get(o);
        if (!orig) originais.set(o, orig = {});
        if (!(k in orig)) orig[k] = v;
        o[k] = curto ? (CURTOS.get(orig[k]) ?? orig[k]) : orig[k];
      }
    };
    visitar(FASES);
    visitar(ILHAS);
  }

  // o nível muda em definirModo (e volta ao padrão em resetar): reaplica os textos
  for (const nome of ['definirModo', 'resetar']) {
    const original = progresso[nome];
    progresso[nome] = (...args) => { const r = original(...args); aplicar(); return r; };
  }
  aplicar();
})();
